### ISSUE TITLE
Missing PKCS12_key_gen_uni 

### ISSUE THREAD

**Issue by KalpaDevOps** [Leseratte10/acsm-calibre-plugin#112]
### Bug description

When using libressl 3.9 i get an error about missing `PKCS12_key_gen_uni ` from libcrypto when trying to get anonymous keys from adobe. Checking the libcrypto.so i see that they are missing. Rolling back to libressl 3.6 gave me a version of libcrypto that included the proper exports.

Googling it briefly, it does look like that function is deprecated, although I also didn't see the `_ex` exports that were supposed to replace it, so I'm not sure if those were deprecated as well?

Running nixos 23/05 for reference, so using an old version of libressl is trivial, but i would think this would have bitten others as well?

### Operating system

Linux

### Which version of Calibre are you running?

7.1

### Which version of the ACSM Input plugin are you running?

master from 11/20/2024

**Comment by botovq** [comment]
This was removed from LibreSSL since nothing in the OpenBSD ports tree used it (and all of PKCS12 is really bad code). If there is a use case, we can consider adding it back in 4.1.0, although I'd really like to know more about it than "when trying to get anonymous keys from adobe". What does this mean?

In any case, this is a LibreSSL issue that should be filed in https://github.com/libressl/portable.

**Comment by ylixir** [comment]
maybe the bug report wasn't clear. The plugin, or maybe one if it's dependencies is attempting to use this "really bad" pkcs12 code. my assumption is that when this code was deprecated, then there was something else available in it's place to perform the same function and that this plugin should be using that code instead of the pkcs12 code. maybe that's not correct? i know basically nothing about encryption. i did not realize that libressl was not a drop in replacement for openssl, or that there would be a reason to use openssl. should i just be using openssl in this case?

to provide more detail: when i click on the button in the picture below while using libressl 3.9, then i get an error about the pkcs12 function not being available.

![clipboard(1)](https://github.com/user-attachments/assets/5d035c4a-542e-4e24-9dc4-d2ba2ea08ed6)

checking libcrypto as a sanity check to make sure it's loading the correct library, i see that it is not there (as expected i suppose)


![image](https://github.com/user-attachments/assets/2d4a168e-69f0-437a-b5d0-bad8f5979245)

so the plugin is attempting to use this old function that is not present on current versions of libressl. if i look at libressl 3.6 i see the function is available:


![image](https://github.com/user-attachments/assets/658cf6af-2c0c-4e5a-aa57-d0cd8770a74f)

indeed, when i use libressl 3.6 instead of 3.9, everything works as it should since those functions are available

also, checking openssl 3.3, i see tha those functions seem to still be present in openssl
![image](https://github.com/user-attachments/assets/3f0c29c3-db32-4747-b2fe-a3d542c893c5)

**Comment by botovq** [comment]
Thanks for the details. It was probably already clear for a user of this plugin, which I'm not. What I was trying to get at is that this is a problem in LibreSSL, not a problem of this plugin.

Yes, the function was deprecated in OpenSSL 3 since they needed the _ex variants for their new API involving libctx and propq. This has nothing directly to do with LibreSSL.

We indeptendently [removed PKCS12_key_gen_uni()][1] from our public API since we could not find uses for much of the PCKS12 API to prepare further removal (we are trying to remove as much low quality code as we can). After half a year yours is the first report I see that had an issue with any of this removal. As mentioned, our testbed is the OpenBSD ports tree, and sometimes we miss some consumers out there. The function is still present in libressl, but as you see, it is no longer exported from the library, so we can add it back in our next release.

I have added this to my list and I will look into it. In the meantime, apologies for the breakage.

**Comment by Leseratte10** [comment]
I can maybe give a bit more context here. This plugin uses [oscrypto](https://github.com/wbond/oscrypto) for cryptographic functions so if there was anything that needed to be changed in how OpenSSL / LibreSSL functions are called, it would most likely need to happen in that library and not directly in my plugin. 

As for the PKCS12 code and the plugin in general using very outdated cryptographic functions and algorithms - that's because it has to emulate ADE which is also using these ancient, legacy, no-longer-recommended algorithms. The plugin receives an encrypted PKCS12 file from Adobe and needs to extract it to get the needed keys, and using oscrypto for that was the only reliable method for that that I was able to get working. 

See the two tests "test_pkcs12_extract" and "test_pkcs12_extract_with_cryptography" in the tests folder. PKCS12, and directly encrypting / decrypting data with plain "textbook" RSA without padding or hashing is done everywhere in the Adobe protocol, and only Adobe could change that to something more modern if they wanted.

**Comment by ylixir** [comment]
Thanks for all the info @botovq and @Leseratte10 and for all the work on the fantastic plugin and crypto library!

I guess I'll close this issue since there is nothing to be done from the plugin at this time and at least this is documented in the issue tracker if anyone else has the same issue.
