### ISSUE TITLE
DRM still present despite importing correctly

### ISSUE THREAD

**Issue by tuzonghua** [Leseratte10/acsm-calibre-plugin#34]
### Bug description

Steps taken:
- Installed / setup DeDRM plugin per README
- Downloaded *.acsm formatted book from Overdrive/Libby
- Imported into Calibre successfully
- When going to open book in built-in Calibre ereader, get error `This book is locked by DRM`

Logs [here](https://pastebin.com/HBwKuxEi).

### Operating system

Windows

### Which version of Calibre are you running?

6.5

### Which version of the DeACSM plugin are you running?

v0.0.16

**Comment by Leseratte10** [comment]
Looking at the log, I can't see any traces of the DeDRM plugin: 

`Successfully initialized third party plugins: DeACSM (0, 0, 16)`. 
That line in the log file is supposed to display the DeDRM plugin, too, so that's not been installed correctly. 

This plugin (ACSM Input) doesn't do any DRM removal by itself. DRM removal is provided by a seperate plugin by another developer, I / my plugin has nothing to do with DRM removal.

**Comment by tuzonghua** [comment]
@Leseratte10 Ah my mistake. However, should I still be able to open a DRM'd ePub in Calibre with this plugin or, like ADE, I'd need to transfer it to a compatible device (e.g., Kobo but not Kindle)? Other than that, we can close this issue. Thanks!

**Comment by Leseratte10** [comment]
No, Calibre cannot open books with DRM at all. This plugin just handles the conversion from ACSM to EPUB (or PDF), it doesn't change anything about the DRM. To open the file, you either need to use a reader that supports DRM, or the DRM needs to be removed.
