### ISSUE TITLE
0.0.16 or 0.1.0 and how to install 0.1.0

### ISSUE THREAD

**Issue by dm82m** [Leseratte10/acsm-calibre-plugin#53]
### Bug description

Thanks for your work. Should I go with official last release 0.0.16 or install current master with 0.1.0? Any advice? And how can I install 0.1.0 if there is no release?

### Operating system

MacOS

### Which version of Calibre are you running?

6.17.0

### Which version of the ACSM Input plugin are you running?

v0.0.16

**Comment by Leseratte10** [comment]
0.1.0 is not released yet because there is still issues when migrating from 0.0.16 to 0.1.0 and I don't want people to lose any data. If you're on a fresh install you might as well start with one of the 0.1.0 beta versions. You can download them from Github Actions (click the "Actions" tab at the top, choose the most recent (= top) workflow run, scroll down to "Artifacts", download "calibre-plugins", and import the "calibre-plugin.zip" inside that file.

**Comment by dm82m** [comment]
@Leseratte10 would you mind running a build again, currently the artifacts for 0.1.0 are no more existing cause the builds are to old
