### ISSUE TITLE
Option to elect ADE version on authorisation missing>

### ISSUE THREAD

**Issue by DB99** [Leseratte10/acsm-calibre-plugin#8]
When I authorise to a new Adobe ID there is no option presented to select the version of ADE as described in the documentation.  Is this no longer an option?  What version of ADE is selected by default?  And thanks for the great work!

**Comment by Leseratte10** [comment]
Hi @DB99, 
the settings to choose between different ADE versions will be added in v0.0.13. That version is currently in beta and you can download it from the linked mobileread thread - I got sidetracked and added a bunch of other experimental stuff in v0.0.13, too, that's why it's still in testing and not fully released yet, even though the README already mentions all that. The latest "stable" version v0.0.12 that's in the github releases doesn't have that feature yet.

v0.0.12 and earlier do not implement a particular ADE version, but its behaviour is closest to ADE 3.0.X.

**Comment by DB99** [comment]
Thank you.  Have instlled beta and is working great.  Thanks for your hard work.
